In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/FDA project/final_edit_2021.csv')

FileNotFoundError: ignored

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df.tail()

        Unnamed: 0      mid      date  ... runs_last_5 innings_run run_sum
200550      200550  1254086  5/2/2021  ...          56         NaN   166.0
200551      200551  1254086  5/2/2021  ...          51         NaN   166.0
200552      200552  1254086  5/2/2021  ...          54         NaN   166.0
200553      200553  1254086  5/2/2021  ...          56         NaN   166.0
200554      200554  1254086  5/2/2021  ...          59       166.0   166.0

[5 rows x 15 columns]

In [ ]:
df=df[df['innings']==1]

In [ ]:
#calculation of the runs
df1=df
runs_tot=[]
runs_a=0
for index, row in df1.iterrows():
  if index<=200554 and index>=0:
    if df1['overs'][index]==0.1:
      runs_a=0
    
    runs_a+=df1['runs'][index]
    runs_tot.append(runs_a)

In [ ]:
len(runs_tot)

103801

In [ ]:
df['runs_tot']=runs_tot

In [ ]:
df.columns

Index(['Unnamed: 0', 'mid', 'date', 'venue', 'bat_team', 'bowl_team',
       'batsman', 'bowler', 'innings', 'runs', 'wickets', 'overs',
       'runs_last_5', 'innings_run', 'run_sum', 'runs_tot'],
      dtype='object')

In [ ]:
#df=df[['striker', 'non_striker', 'Wicket', 'overs','run_sum','innings','runs_off_bat','player_dismissed','runs_tot']]
df.head(50)

    Unnamed: 0     mid       date  ... innings_run run_sum runs_tot
0            0  335982  4/18/2008  ...         NaN   221.0        1
1            1  335982  4/18/2008  ...         NaN   221.0        1
2            2  335982  4/18/2008  ...         NaN   221.0        2
3            3  335982  4/18/2008  ...         NaN   221.0        2
4            4  335982  4/18/2008  ...         NaN   221.0        2
5            5  335982  4/18/2008  ...         NaN   221.0        2
6            6  335982  4/18/2008  ...         NaN   221.0        3
7            7  335982  4/18/2008  ...         NaN   221.0        3
8            8  335982  4/18/2008  ...         NaN   221.0        7
9            9  335982  4/18/2008  ...         NaN   221.0       11
10          10  335982  4/18/2008  ...         NaN   221.0       17
11          11  335982  4/18/2008  ...         NaN   221.0       21
12          12  335982  4/18/2008  ...         NaN   221.0       21
13          13  335982  4/18/2008  ...         NaN   221.0       21
14          14  335982  4/18/2008  ...         NaN   221.0       21
15          15  335982  4/18/2008  ...         NaN   221.0       22
16          16  335982  4/18/2008  ...         NaN   221.0       26
17          17  335982  4/18/2008  ...         NaN   221.0       27
18          18  335982  4/18/2008  ...         NaN   221.0       27
19          19  335982  4/18/2008  ...         NaN   221.0       32
20          20  335982  4/18/2008  ...         NaN   221.0       38
21          21  335982  4/18/2008  ...         NaN   221.0       39
22          22  335982  4/18/2008  ...         NaN   221.0       43
23          23  335982  4/18/2008  ...         NaN   221.0       43
24          24  335982  4/18/2008  ...         NaN   221.0       44
25          25  335982  4/18/2008  ...         NaN   221.0       50
26          26  335982  4/18/2008  ...         NaN   221.0       54
27          27  335982  4/18/2008  ...         NaN   221.0       55
28          28  335982  4/18/2008  ...         NaN   221.0       59
29          29  335982  4/18/2008  ...         NaN   221.0       59
30          30  335982  4/18/2008  ...         NaN   221.0       60
31          31  335982  4/18/2008  ...         NaN   221.0       60
32          32  335982  4/18/2008  ...         NaN   221.0       61
33          33  335982  4/18/2008  ...         NaN   221.0       61
34          34  335982  4/18/2008  ...         NaN   221.0       61
35          35  335982  4/18/2008  ...         NaN   221.0       61
36          36  335982  4/18/2008  ...         NaN   221.0       61
37          37  335982  4/18/2008  ...         NaN   221.0       61
38          38  335982  4/18/2008  ...         NaN   221.0       62
39          39  335982  4/18/2008  ...         NaN   221.0       63
40          40  335982  4/18/2008  ...         NaN   221.0       64
41          41  335982  4/18/2008  ...         NaN   221.0       66
42          42  335982  4/18/2008  ...         NaN   221.0       67
43          43  335982  4/18/2008  ...         NaN   221.0       68
44          44  335982  4/18/2008  ...         NaN   221.0       68
45          45  335982  4/18/2008  ...         NaN   221.0       69
46          46  335982  4/18/2008  ...         NaN   221.0       70
47          47  335982  4/18/2008  ...         NaN   221.0       71
48          48  335982  4/18/2008  ...         NaN   221.0       72
49          49  335982  4/18/2008  ...         NaN   221.0       73

[50 rows x 16 columns]

In [ ]:
#filter for the first innings
df=df[df['innings']==1]

In [ ]:
df1=df
person_a=df['striker'][0]    
person_b=df['non_striker'][0]
runs_a=0
runs_b=0
list_a=[]
list_b=[]

for index, row in df1.iterrows():
  #when there is no change in wicket, initialize the 2 players as a and b
  #exept when it is the start of the over, then initialize the players as a and b
  
  #initializing the person_a and person_b
  if index<=100190 and index>=0:

    if df1['overs'][index]==0.1:
      person_a=df1['striker'][index]
      person_b=df1['non_striker'][index]
      runs_a=0
      runs_b=0
      #print("visited first if initialize")

    elif not pd.isnull(df1.loc[index]['player_dismissed']):
      #change the person who lost the wicket
      #print("visited second if initialize")
      if person_a == df1.loc[index]['player_dismissed']:
        runs_a=0
        #update to the new person        
        x=[person_a,person_b]
        new_player=" "
        if df1['striker'][index+1] in x:
          new_player=df1['non_striker'][index+1]
        else:
          new_player=df1['striker'][index+1]        
        person_a=new_player
        
      else:
        runs_b=0
        #update to the new person        
        x=[person_a,person_b]
        new_player=" "
        if df1['striker'][index+1] in x:
          new_player=df1['non_striker'][index+1]
        else:
          new_player=df1['striker'][index+1]        
        person_b=new_player

    #adding the runs to the list
    if df['striker'][index]==person_a:
      # print(runs_a)
      runs_a+=df['runs_off_bat'][index]
      #print(df['runs_off_bat'][index])
      #print("runs scored by a is {} at index {}".format(runs_a,index))
      list_a.append(runs_a)
      list_b.append(runs_b)
    else:
      #print(runs_b)
      runs_b+=df['runs_off_bat'][index]
      #print(df['runs_off_bat'][index])
      #print("runs scored by b is {} at index {}".format(runs_b,index))
      list_a.append(runs_a)
      list_b.append(runs_b)

KeyError: ignored

In [ ]:
df1.shape

(100191, 9)

In [ ]:
required_striker=max(list_a,list_b)
required_non_striker=min(list_a,list_b)

In [ ]:
df['required_striker']=required_striker
df['required_non_striker']=required_non_striker

In [ ]:
df.head()

       striker  non_striker  ...  required_striker  required_non_striker
0   SC Ganguly  BB McCullum  ...                 0                     0
1  BB McCullum   SC Ganguly  ...                 0                     0
2  BB McCullum   SC Ganguly  ...                 0                     0
3  BB McCullum   SC Ganguly  ...                 0                     0
4  BB McCullum   SC Ganguly  ...                 0                     0

[5 rows x 10 columns]

In [ ]:
df1.to_csv('ready_for_ml.csv')

In [ ]:
df1=df[df['innings']==1]

In [ ]:
df1.shape

(100191, 10)

In [ ]:
df3=pd.read_csv('ready_for_ml.csv')

In [ ]:
df3.shape

(100191, 11)

In [ ]:
df3.columns

Index(['Unnamed: 0', 'striker', 'non_striker', 'Wicket', 'overs', 'run_sum',
       'innings', 'runs_off_bat', 'player_dismissed', 'required_striker',
       'required_non_striker', 'runs'],
      dtype='object')

In [ ]:
df3['runs']=runs_tot

In [ ]:
df3.tail()

        Unnamed: 0   striker  ... required_non_striker  runs
100186      193500  AR Patel  ...                    0   149
100187      193501   SS Iyer  ...                    0   149
100188      193502   SS Iyer  ...                    0   149
100189      193503   SS Iyer  ...                    0   155
100190      193504   SS Iyer  ...                    0   156

[5 rows x 12 columns]

In [ ]:
df3.to_csv('ready_for_ml_v1.csv')